### ISSUE TITLE
[Bug] denotationChar becomes null in mention

### ISSUE THREAD

**Issue by webmarket7** [afconsult/quill-mention#16]
Hi! 
First of all let me thank you for such a nice solution!

But i have found a bug, while trying to use this in my project. Sometimes null is added instead of denotation char to mention blot.

I guess, I have found the reason for this behaviour. Please see screenshot attached below.

![default](https://user-images.githubusercontent.com/25647312/40848342-95c646dc-65c7-11e8-8a40-274ebefd1eb1.png)

I commented out this row, and the problem has gone.

It would be very nice if you could come up with some fix for this issue.

Cheers!

**Comment by MadSpindel** [comment]
Ping @cwhite-connectfirst

**Comment by cwhite-connectfirst** [comment]
@webmarket7 good catch. I'll submit a PR for this shortly.

**Comment by cwhite-connectfirst** [comment]
@MadSpindel Just curious - was there an intent to support a custom `renderList` function? I see that we're storing a bound reference to `renderList` on the options object (https://github.com/afconsult/quill-mention/blob/master/src/quill.mention.js#L29). It doesn't seem like that was the case, but I wanted to check with you first. `renderList` isn't mentioned in the documentation as a valid option right now. Also, if a custom `renderList` function is supposed to be a supported feature, it's not working correctly right now, since we're not referencing the `renderList` function stored on the `options` object when calling `source` (https://github.com/afconsult/quill-mention/blob/master/src/quill.mention.js#L244).

Personally, I don't think it makes much sense to let users override the renderList function with their own definition, since `renderList` is responsible for modifying instance properties. I'm going to submit this PR with `renderList` removed from the options object, but if you think it should be a valid option, let me know and I can revert that change from my PR.

**Comment by cwhite-connectfirst** [comment]
PR https://github.com/afconsult/quill-mention/pull/17

**Comment by MadSpindel** [comment]
@cwhite-connectfirst Yeah, I think we should remove renderList from this.options and only pass the reference. Is it something you want to do in your pull request now or should I merge it as is?

**Comment by cwhite-connectfirst** [comment]
@MadSpindel I can do that in my PR, since it's an easy change. It also cleans up my fix a bit.

**Comment by cwhite-connectfirst** [comment]
Just pushed those changes

**Comment by MadSpindel** [comment]
Yes, thank you @cwhite-connectfirst! I will release this as v2.0.0
