### ISSUE TITLE
Wrong insertion when exist previous mention denotation char

### ISSUE THREAD

**Issue by soyJairoCosta** [afconsult/quill-mention#82]
Hi!

I was trying this use case:

![image](https://user-images.githubusercontent.com/34161690/60339867-45707a00-99aa-11e9-8652-5b7a20532434.png)
But, when I tried to mention anyone this happen:

![image](https://user-images.githubusercontent.com/34161690/60339905-5faa5800-99aa-11e9-8f58-62f160ffab0f.png)

![image](https://user-images.githubusercontent.com/34161690/60339967-8c5e6f80-99aa-11e9-9e0d-bf5a1378ba31.png)

So the mention inserts itself before the previous '@'.

I hope you can fix this issue... I love this project :D

**Comment by t3chnoboy** [comment]
We're experiencing the same issue. 
It only happens when you press `enter` or `tab` and works fine if you click the dropdown,
which is weird because `enter` and `tab` handlers call the same function as `onClick`:
https://github.com/afconsult/quill-mention/blob/master/src/quill.mention.js#L100
https://github.com/afconsult/quill-mention/blob/master/src/quill.mention.js#L220

So it might be an issue with Quill itself 😕

**Comment by hamza962212** [comment]
#87 the issue was with the location being changed when delete function is called. So a short fix for you 🎉 🎉 enjoy!

**Comment by soyJairoCosta** [comment]
@hamza962212 your commit works like a charm!!

Thanks a lot :D
